spring:
  jackson:
    time-zone: GMT+8
  data:
    mongodb:
      host: 112.74.187.216
      port: 27017
      database: stockHistoryPrice
      username: root
      password: Root.123456
      authentication-database: admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASS}
    url: jdbc:mysql://${MYSQL_HOST}/found_trading?characterEncoding=utf-8&useSSL=false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    timeout: 10000
    url: redis://:${REDIS_PASS}@${REDIS_HOST}
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        #连接超时时间