# 声明StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: found-front
  labels:
    app: found-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: found-front
  serviceName: found-front
  template:
    metadata:
      labels:
        app: found-front
    spec:
      imagePullSecrets:
      - name: mwangli-docker-secret
      containers:
      - image: registry-vpc.cn-shenzhen.aliyuncs.com/mwangli/found-front
        imagePullPolicy: Always
        name: found-front
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
      volumes:
        # 挂载配置到configMap
        - name: nginx-config
          configMap:
            name: nginx-conf
            items:
            - key: nginx.conf
              path: nginx.conf
---
# 声明ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
#  namespace: dafault
data:
  nginx.conf: |
   server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
     location ^~/api/  {
        proxy_pass http://mwang.online:8080/;
    }
   }
---
# 声明Service服务
apiVersion: v1
kind: Service
metadata:
  name: found-front-svc
  labels:
    app: found-front
spec:
  type: NodePort
  selector:
    app: found-front
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 8000
---
# 镜像仓库密钥
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS12cGMuY24tc2hlbnpoZW4uYWxpeXVuY3MuY29tIjp7InVzZXJuYW1lIjoibGltaW5nd2FuZzA2IiwicGFzc3dvcmQiOiJEa25oZnJlMXN0IiwiYXV0aCI6ImJHbHRhVzVuZDJGdVp6QTJPa1JyYm1obWNtVXhjM1E9In19fQ==
metadata:
  name: mwangli-docker-secret
  namespace: default
