name: deploy

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: mvn-package
      run: mvn package
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag found-trading
