name: deploy

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 拉取代码
    - uses: actions/checkout@v3
    # 打包文件
    - name: mvn-package
      run: mvn package
    # 构建镜像
    - name: docker-build
      run: |
        APP=found-trading
        REGISTER=registry.cn-shenzhen.aliyuncs.com
        NS=mwangli
        USER=limingwang06
        PASS=Dknhfre1st
        HOST=112.74.187.216
        docker build -t $APP -f Dockerfile .
        docker login --username=${{secrets.REGISTRY_USERNAME}} --password=${{secrets.REGISTRY_PASSWORD}} $REGISTER
        docker tag $APP $REGISTER/$NS/$APP
        docker push $REGISTER/$NS/$APP
        ssh root@$HOST kubectl set image sts/$APP $APP=$REGISTER/$NS/$APP --record
        Dknhfre1st