name: deploy

on: [ push ]

jobs:
  #  build:
  #    runs-on: ubuntu-latest
  #    steps:
  #      # 拉取代码
  #      - uses: actions/checkout@v3
  #      # 打包文件
  #      - name: mvn-package
  #        run: mvn clean package
  #      # 构建镜像
  #      - name: docker-build
  #        env:
  #          APP: found-trading
  #          REGISTER: registry.cn-shenzhen.aliyuncs.com
  #          NS: mwangli
  #          USER: limingwang06
  #          PASS: Dknhfre1st
  #        run: |
  #          docker login --username=$USER --password=$PASS $REGISTER
  #          docker build -t $APP -f Dockerfile .
  #          docker tag $APP $REGISTER/$NS/$APP
  #          docker push $REGISTER/$NS/$APP
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup-SSH
        env:
          KEY: ${{ secrets.PRIVATE_KEY }}
        uses: MrSquaare/ssh-setup-action@v2
        with:
          host: 112.74.187.216
          private-key: $KEY
      - name: ssh-cmd
        run: |
          ssh root@112.74.187.216 kubectl get pod
