name: deploy

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      # 拉取代码
#      - uses: actions/checkout@v3
#      # 打包文件
#      - name: mvn-package
#        run: mvn package
#      # 构建镜像
#      - name: docker-build
#        env:
#          APP: test
#          REGISTER: registry.cn-shenzhen.aliyuncs.com
#          NS: mwangli
#          USER: limingwang06
#          PASS: Dknhfre1st
#        run: |
#           docker build -t ${APP} -f Dockerfile .
#           docker login --username=${USER} --password=${PASS} ${REGISTER}
#           docker tag ${APP} ${REGISTER}/${NS}/${APP}
#           docker push ${REGISTER}/${NS}/${APP}
      # 重启服务
      - uses: kevin-leptons/ssh_action@v1
        with:
          # URI refers to remote host like `user@host`
          host: root@112.74.187.216
          # Private SSH key to authenticate
          key: ${{ secrets.PRIVATE_KEY }}
          # Command to execute, Bash syntax
          command: pwd && ls