name: deploy

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: mvn package
        run: |
          pwd
          dcoker info
          java -version
          ls /home/runner/
