


name: deploy

on: [ push ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
            java-version: 1.8
      - name: test
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.REGISTRY }}
        run: |
          echo "github action test"
