name: deploy

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - uses: actions/checkout@v2
      # Docker环境
      - uses: docker/setup-buildx-action@v2
      # 打包镜像
      - name: mvn-build
        run: |
          mvn clean compile package
          /usr/bin/dcoker -version
        
