name: deploy

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - uses: actions/checkout@v2
      # Docker环境
      - uses: docker/setup-buildx-action@v2
      # 打包镜像
      - name: mvn-build
        run: |
          mvn clean compile package
          /usr/bin/docker info
          APP=found-trading
          REGISTER=registry-vpc.cn-shenzhen.aliyuncs.com
          NS=mwangli
          USER=limingwang06
          PASS=Dknhfre1st
          /usr/bin/docker build -t $APP -f Dockerfile .
          /usr/bin/docker login --username=$USER --password=$PASS $REGISTER
          /usr/bin/docker tag $APP $REGISTER/$NS/$APP
          /usr/bin/docker push $REGISTER/$NS/$APP
        
