name: deploy

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
            java-version: 1.8
      - name: mvn package
        run: |
          mvn clean package
