name: deploy

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - uses: actions/checkout@v2
      # Docker环境
      - uses: docker/setup-buildx-action@v2
      # Dokcer登录
      - uses: docker/login-action@v2.1.0
        with:
          registry: registry-vpc.cn-shenzhen.aliyuncs.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      # 打包镜像
      - name: build
        run: |
          mvn clean compile package
          APP=found-trading
          REGISTER=registry-vpc.cn-shenzhen.aliyuncs.com
          NS=mwangli
          /usr/bin/docker build -t $APP -f Dockerfile .
          /usr/bin/docker tag $APP $REGISTER/$NS/$APP
          /usr/bin/docker push $REGISTER/$NS/$APP
        
