name: deploy

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.5.0
      - name: mvn package
        run: |
          pwd
          dcoker info
          java -version
          ls /home/runner/
