name: deploy

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout Code
        uses: actions/checkout@v2
      # JDK环境
      - name: SetUP JDK
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Docker环境
      - name: SetUP Docker
        uses: docker/setup-buildx-action@v1
      # 验证环境
      - name: test-env
        run: |
          java -version
          mvn -version
          dcoker -version
        
